# Generated by Django 5.2.5 on 2025-08-20 20:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='tempuser',
            name='uniq_active_temp_email',
        ),
        migrations.AddConstraint(
            model_name='tempuser',
            constraint=models.UniqueConstraint(condition=models.Q(('is_used', False), ('token_expires_at__gt', datetime.datetime(2025, 8, 20, 20, 8, 35, 208723, tzinfo=datetime.timezone.utc))), fields=('email',), name='uniq_active_temp_email'),
        ),
    ]
