# Generated by Django 5.2.5 on 2025-08-23 22:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_tempuser_uniq_active_temp_email_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='tempuser',
            name='uniq_active_temp_email',
        ),
        migrations.AddConstraint(
            model_name='tempuser',
            constraint=models.UniqueConstraint(condition=models.Q(('is_used', False), ('token_expires_at__gt', datetime.datetime(2025, 8, 23, 22, 0, 14, 434233, tzinfo=datetime.timezone.utc))), fields=('email',), name='uniq_active_temp_email'),
        ),
    ]
