# Generated by Django 5.2.5 on 2025-08-26 20:00

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_tempuser_uniq_active_temp_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TempAdmin',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=128)),
                ('password_hash', models.CharField(max_length=128)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('is_platform_staff', models.BooleanField()),
                ('is_platform_admin', models.BooleanField()),
                ('verification_token', models.CharField(max_length=200, unique=True)),
                ('token_expires_at', models.DateTimeField()),
                ('is_used', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='tempuser',
            name='uniq_active_temp_email',
        ),
    ]
