# Generated by Django 5.2.6 on 2025-09-07 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_tempadmin_remove_tempuser_uniq_active_temp_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='tempadmin',
            name='country',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
