# Generated by Django 5.2.5 on 2025-09-09 16:05

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_tempadmin_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='TempInvitedUser',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('role', models.CharField(max_length=20)),
                ('token', models.CharField(max_length=64, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('is_used', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending_invites', to='accounts.account')),
                ('invited_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_invites', to='accounts.user')),
            ],
            options={
                'indexes': [models.Index(fields=['account', 'email'], name='accounts_te_account_3161a0_idx'), models.Index(fields=['token'], name='accounts_te_token_9c355e_idx')],
            },
        ),
    ]
